# Generated by Django 3.2.9 on 2022-07-31 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20220731_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='image',
        ),
    ]
