# Generated by Django 3.2.9 on 2022-07-31 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_remove_team_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fistname', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='photos')),
                ('description', models.TextField(max_length=200)),
                ('facebook', models.URLField(max_length=100)),
                ('twitter', models.URLField(max_length=100)),
                ('google', models.URLField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
