# Generated by Django 3.2.9 on 2022-07-31 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_auto_20220731_1908'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teams',
            new_name='Team',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='fistname',
            new_name='firstname',
        ),
    ]
